version: '3.8'
services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build: 
      context: ./ClassroomBooking.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=database;Database=ClassroomBookingDB;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true;
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./classroom-booking-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  sqlserver_data: